#hw3_p2_docker-compose.yml
#the hw3_python docker image was made to process the input_files 
#four containers are created from the hw3_python image, and each of them processes one input file
#this docker-compose file should be run after hw3_redis_docker-compose.yml is up
version: '3'

services:

  python_client1:
    image: hw3_python
    container_name: python_client1
    command: bash -c "python hw3_problem2.py 'input_files/file-input1.csv' "

  python_client2:
    image: hw3_python
    container_name: python_client2
    command: bash -c "python hw3_problem2.py 'input_files/file-input2.csv' "

  python_client3:
    image: hw3_python
    container_name: python_client3
    command: bash -c "python hw3_problem2.py 'input_files/file-input3.csv' "

  python_client4:
    image: hw3_python
    container_name: python_client4
    command: bash -c "python hw3_problem2.py 'input_files/file-input4.csv' "